### ISSUE TITLE
Status descriptors don't work

### ISSUE THREAD

**Issue by Froozigiusz** [frigid14/frigid-old#99]
I don't think they would be changed from SS14 descriptions as they are quite agnostic, but despite that they borked.

![Zrzut ekranu z 2022-10-23 16-04-45](https://user-images.githubusercontent.com/77325322/197397104-656591c2-6107-4757-b976-78a3de7b3ad6.png)

**Comment by Just-a-Unity-Dev** [comment]
Can't repro on latest master.

![image](https://user-images.githubusercontent.com/67359748/198994203-abe23c52-aa53-4668-bb88-b943a4035b50.png)
![image](https://user-images.githubusercontent.com/67359748/198994230-c97cd524-143e-4954-b5d7-8c2b34e1bac0.png)
